name: Check Answers

on:
  push:

jobs:
  check-answers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Check Question 1
        run: |
          answer=$(grep "Answer:" questions/question1.txt | sed 's/Answer://:' | tr '[:upper:]' '[:lower:]' | xargs)

          if [ "$answer" = "mouse" ]; then
            echo "Question 1 correct"
          else
            echo "Question 1 incorrect"
            exit 1
          fi

      - name: Check Question 2
        run: | 
          answer=$(grep "Answer:" questions/question2.txt | sed 's/Answer://:' | tr '[:upper:]' '[:lower:]' | xargs)

          if [ "$answer" = "code" ]; then
            echo "Question 2 correct"
          else
            echo "Question 2 incorrect"
            exit 1
          fi
          
      - name: Check Question 3
        run: |
          answer=$(grep "Answer:" questions/question3.txt | sed 's/Answer://:' | tr '[:upper:]' '[:lower:]' | xargs)

          if [ "$answer" = "gummy bear" ]; then
            echo "Question 3 correct"
          else
            echo "Question 3 incorrect"
            exit 1
          fi

      - name: Check Question 4
        run: |
          answer=$(grep "Answer:" questions/question4.txt | sed 's/Answer://:' | tr '[:upper:]' '[:lower:]' | xargs)

          if [ "$answer" = "keyboard" ]; then
            echo "Question 4 correct"
          else
            echo "Question 4 incorrect"
            exit 1
          fi

      - name: Check Question 5
        run: |
          answer=$(grep "Answer:" questions/question5.txt | sed 's/Answer://:' | tr '[:upper:]' '[:lower:]' | xargs)

          if [ "$answer" = "ton" ]; then
            echo "Question 5 correct"
          else
            echo "Question 5 incorrect"
            exit 1
          fi
