name: Check Answers

on:
  push:

jobs:
  check-answers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Check Question 1
        run: 
          answer=$(cat question1.txt)

          if ["$answer" = "mouse"]; then
            echo "Question 1 correct"
          else
            echo "Question 1 incorrect"
            exit 1
          fi

      - name: Check Question 2
        run: 
          answer=$(cat question2.txt)

          if ["$answer" = "${{ secrets.Q2_ANSWER }}"]; then
            echo "Question 2 correct"
          else
            echo "Question 2 incorrect"
            exit 1
          fi
          
      - name: Check Question 3
        run: 
          answer=$(cat question3.txt)

          if ["$answer" = "${{ secrets.Q3_ANSWER }}"]; then
            echo "Question 3 correct"
          else
            echo "Question 3 incorrect"
            exit 1
          fi

      - name: Check Question 4
        run: 
          answer=$(cat question4.txt)

          if ["$answer" = "${{ secrets.Q4_ANSWER }}"]; then
            echo "Question 4 correct"
          else
            echo "Question 4 incorrect"
            exit 1
          fi

      - name: Check Question 5
        run: 
          answer=$(cat question5.txt)

          if ["$answer" = "${{ secrets.Q5_ANSWER }}"]; then
            echo "Question 5 correct"
          else
            echo "Question 5 incorrect"
            exit 1
          fi
